//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratoreSit.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneratoreSit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a body.stop-scrolling {
        ///  height: 100%;
        ///  overflow: hidden; }
        ///
        ///.sweet-overlay {
        ///  background-color: black;
        ///  /* IE8 */
        ///  -ms-filter: &quot;progid:DXImageTransform.Microsoft.Alpha(Opacity=40)&quot;;
        ///  /* IE8 */
        ///  background-color: rgba(0, 0, 0, 0.4);
        ///  position: fixed;
        ///  left: 0;
        ///  right: 0;
        ///  top: 0;
        ///  bottom: 0;
        ///  display: none;
        ///  z-index: 10000; }
        ///
        ///.sweet-alert {
        ///  background-color: white;
        ///  font-family: &apos;Open Sans&apos;, &apos;Helvetica Neue&apos;, Helvetica, Arial, sans-serif;
        ///  width: 478px;
        ///  padding: 17px [stringa troncata]&quot;;.
        /// </summary>
        internal static string sweetalert {
            get {
                return ResourceManager.GetString("sweetalert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ;(function(window, document, undefined) {
        ///  &quot;use strict&quot;;
        ///  
        ///  (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require==&quot;function&quot;&amp;&amp;require;if(!u&amp;&amp;a)return a(o,!0);if(i)return i(o,!0);var f=new Error(&quot;Cannot find module &apos;&quot;+o+&quot;&apos;&quot;);throw f.code=&quot;MODULE_NOT_FOUND&quot;,f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require==&quot;function&quot;&amp;&amp;require;for(var o=0;o&lt;r.length;o++)s(r[o]);return s})({1: [stringa troncata]&quot;;.
        /// </summary>
        internal static string sweetalert_dev {
            get {
                return ResourceManager.GetString("sweetalert_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac sapien non lectus faucibus auctor. Donec sollicitudin eget justo ac eleifend. Nulla semper mauris sem, ut hendrerit diam finibus at. Etiam tempor justo scelerisque, convallis lorem eu, tincidunt arcu. Vivamus vel maximus nisi. Proin neque augue, convallis eu accumsan a, molestie ac ex. Mauris suscipit porttitor ultricies. Praesent efficitur magna et nisi lobortis, quis mollis ipsum mattis. Suspendisse vitae risus tortor. Donec eu quam nibh. Cra [stringa troncata]&quot;;.
        /// </summary>
        internal static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
    }
}
