//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratoreSit.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneratoreSit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 		&lt;div class=&quot;row&quot;&gt;
        ///		&lt;div class=&quot;col-xs-12 col-sm-12 col-md-3 text-center&quot;&gt;&lt;/div&gt;
        ///			&lt;div class=&quot;col-xs-12 col-sm-12 col-md-6 text-center shadow rounded tutto&quot;&gt;
        ///				&lt;h1&gt;&lt;b&gt;About&lt;/b&gt;&lt;/h1&gt;
        ///			&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		&lt;style&gt;
        ///		.social-menu {
        ///			display: flex;
        ///			list-style-type: none;
        ///		}
        ///		 
        ///		.social-menu i {
        ///			color: #fff;
        ///			width: 40px;
        ///			height: 40px;
        ///			border-radius: 50%;
        ///			font-size: 25px;
        ///			margin-right: 10px;
        ///			transition: all 0.2s ease-in-out;
        ///			display: flex;
        ///			justify-conte [stringa troncata]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 
        ///.tutto {
        ///	background-color: rgba(255, 255, 255, 0.3);
        ///	border: 1px solid;
        ///	padding: 10px;
        ///	box-shadow: 5px 10px 8px #888888;
        ///	vertical-align: middle;
        ///}
        ///.bottone {
        ///	margin-bottom: 4px;
        ///	margin-top: 4px;
        ///}
        ///
        ///.row {
        ///	padding-top: 10px;
        ///}
        ///
        ///.muovi:hover {
        ///  /* Start the shake animation and make the animation last for 0.5 seconds */
        ///  animation: shake 0.5s;
        ///
        ///  /* When the animation is finished, start again */
        ///  animation-iteration-count: infinite;
        ///}
        ///
        ///@keyframes shake {
        ///  0% { transform:  [stringa troncata]&quot;;.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] menu {
            get {
                object obj = ResourceManager.GetObject("menu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac sapien non lectus faucibus auctor. Donec sollicitudin eget justo ac eleifend. Nulla semper mauris sem, ut hendrerit diam finibus at. Etiam tempor justo scelerisque, convallis lorem eu, tincidunt arcu. Vivamus vel maximus nisi. Proin neque augue, convallis eu accumsan a, molestie ac ex. Mauris suscipit porttitor ultricies. Praesent efficitur magna et nisi lobortis, quis mollis ipsum mattis. Suspendisse vitae risus tortor. Donec eu quam nibh. Cra [stringa troncata]&quot;;.
        /// </summary>
        internal static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
    }
}
